version: 2

sources:
  - name: redshift-cluster-2
    database: cascade
    schema: sightings
    tables:
      - name: stg_europe
      - name: stg_america
      - name: stg_indian
      - name: stg_africa
      - name: stg_pacific
      - name: stg_atlantic
      - name: stg_australia
      - name: stg_asia
      - name: all_regions