version: 2

sources:
  - name: redshift-cluster-2
    database: cascade
    schema: sightings
    tables:
      - name: europe
      - name: america
      - name: indian
      - name: africa
      - name: pacific
      - name: atlantic
      - name: australia
      - name: asia